csv_name: train
code_root_dir: /work/liuzehua/task/VSR/cnvsrc
audio_data_root_dir: /work/liuzehua/task/VSR/data/LRS/LRS2-BBC
video_data_root_dir: /work/liuzehua/task/VSR/data/LRS/LRS2-BBC
k_means_model: /work/liuzehua/task/VSR/cnvsrc/vsr2asr/model5/Phase1_k-means_cluster/kmeans_model.joblib
hubert_model: /work/liuzehua/task/VSR/cnvsrc/vsr2asr/model5/English-hubert-large
gpus: 1
pretrained_model: /work/liuzehua/task/VSR/cnvsrc/main_log/2024-09-10/21-09-54-model5-Phase3-vsr2asr-v2-lrs2-4s-model3/model/epoch=39-valid_asr2vsr_decoder_acc=0.4121.ckpt
CAM_path: /work/liuzehua/task/VSR/cnvsrc/main_log/2024-08-29/20-39-09-model5-Phase2-asr/model/epoch=79-train_loss=19.67.ckpt
loss:
  asr2vsr_att_w: 0.9
  ctc_w: 0.1
  a2v_attscore:
    step: 2
    window_size: 3
    a2v_attscore_w: 8
save:
  save_path: /work/liuzehua/task/VSR/cnvsrc/main_log/2024-09-01/00-37-49-model5-Phase3-vsr2asr-v2-lrs2
  tblog_dir: ${save.save_path}/tblog
  hydra_dir: ${save.save_path}
  trainer_save_dir: ${save.save_path}
  save_train_model: ${save.save_path}/model
  save_valid_model: ${save.save_path}/model
  save_train_topk: 5
  save_valid_topk: 10
trainer:
  precision: 32
  max_epochs: 40
  gpus: -1
  sync_batchnorm: true
  default_root_dir: ${save.trainer_save_dir}
  num_sanity_val_steps: 0
  limit_val_batches: 1.0
  accumulate_grad_batches: 1
  gradient_clip_val: 5.0
  replace_sampler_ddp: false
  # resume_from_checkpoint: /work/liuzehua/task/VSR/cnvsrc/main_log/2024-09-03/10-26-00-model5-Phase3-vsr2asr-v2-lrs2/model/last.ckpt
optimizer:
  name: adamw
  lr: 0.00007
  warmup_epochs: 2
  weight_decay: 0.0004
  betas:
  - 0.9
  - 0.98
data:
  batch_max_frames: 1000
  max_frames: 125
  max_frames_val: 1000
  dataset:
    root: ${code_root_dir}
    label_dir: /work/liuzehua/task/VSR/cnvsrc/data/vsr2asr/model5/Phase3/LRS2
    train_file: ${csv_name}.csv
    val_file: test.csv
    test_file: test.csv
    num_workers: 16
model:
  visual_backbone:
    adim: 768
    aheads: 12
    eunits: 3072
    elayers: 4
    transformer_input_layer: conv3d
    dropout_rate: 0.1
    transformer_attn_dropout_rate: 0.1
    transformer_encoder_attn_layer_type: rel_mha
    macaron_style: true
    use_cnn_module: true
    cnn_module_kernel: 31
    zero_triu: false
    a_upsample_ratio: 1
    relu_type: swish
    ddim: ${model.visual_backbone.adim}
    dheads: ${model.visual_backbone.aheads}
    dunits: 3072
    dlayers: 6
    lsm_weight: 0.1
    transformer_length_normalized_loss: false
    mtlalpha: 0.1
    ctc_type: builtin
    rel_pos_type: latest
  Hybird_AVEncoder:
    num_layers: 4
    abm:
      embed_size: 768
      num_heads: 12
      num_layers: 1
      dropout_rate: 0.1
  Bi_transformer_decoder:
    exist: true
    layers: 3
  audio_backbone:
    adim: 768
    aheads: 12
    eunits: 3072
    elayers: 12
    transformer_input_layer: conv1d
    dropout_rate: 0.1
    transformer_attn_dropout_rate: 0.1
    transformer_encoder_attn_layer_type: rel_mha
    macaron_style: true
    use_cnn_module: true
    cnn_module_kernel: 31
    zero_triu: false
    a_upsample_ratio: 1
    relu_type: swish
    ddim: ${model.audio_backbone.adim}
    dheads: ${model.audio_backbone.aheads}
    dunits: 3072
    dlayers: 6
    lsm_weight: 0.1
    transformer_length_normalized_loss: false
    mtlalpha: 0.1
    ctc_type: builtin
    rel_pos_type: latest


hydra:
  run:
    dir: ${save.hydra_dir}
  job_logging:
    root:
      handlers: [console, file]
      level: DEBUG
    handlers:
      file:
        class: logging.FileHandler
        formatter: simple
        mode: a
    formatters:
      simple:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'



